import 'jss-compose/tests/index.test'
import 'jss-nested/tests/index.test'
import 'jss-expand/tests/index.test'
import 'react-jss/tests/index.test'

import './integration/jss'
import './integration/rules'
import './integration/sheet'
import './functional/priority'
import './functional/rules'
import './functional/sheet'
