/* eslint-disable import/first */

import './utils'
import 'jss-compose/tests/index.test'
import 'jss-nested/tests/index.test'
import 'jss-expand/tests/index.test'
import 'jss-default-unit/tests/index.test'
import 'jss-camel-case/tests/index.test'
import 'jss-extend/tests/index.test'
import 'jss-isolate/tests/index.test'
import 'jss-global/tests/index.test'
import './integration/jss'
import './integration/rules'
import './integration/sheet'
import './integration/SheetsRegistry'
import './functional/rules'
import './functional/sheet'
import './functional/priority'
