'use strict'

var Rule = require('./Rule')

/**
 * Creates style element, contains rules, injects style into dom.
 *
 * @param {Object} [rules] object with selectors and declarations
 * @param {Object} [attributes] style element attributes
 * @api public
 */
function Style(rules, attributes) {
    this.element = null
    this.rules = {}
    this.attributes = attributes || {}
    if (!this.attributes.type) this.attributes.type = 'text/css'
    if (!this.attributes.media) this.attributes.media = 'screen'
    if (!this.attributes.title) this.attributes.title = 'Generated by jss.'

    for (var selector in rules) {
        this.rules[selector] = new Rule(selector, rules[selector])
        this.rules[selector].extractScopedRules().forEach(function (rule) {
            this.rules[rule.selector] = rule
        }, this)
    }

    this.text = this.toString()
    this.attached = false
}

module.exports = Style

/**
 * Insert style element to render tree.
 *
 * @api public
 * @return {Style}
 */
Style.prototype.attach = function () {
    if (this.attached) return this

    if (!this.element) this.element = this.createElement()
    this.element.innerHTML = this.text
    if (!this.element.parentNode) document.head.appendChild(this.element)
    this.attached = true

    return this
}

/**
 * Remove style element from render tree.
 *
 * @return {Style}
 * @api public
 */
Style.prototype.detach = function () {
    if (!this.attached) return this

    this.element.parentNode.removeChild(this.element)
    this.attached = false

    return this
}

/**
 * Add a rule.
 *
 * @param {Object} [selector] if you don't pass selector - it will be generated
 * @param {Object} style property/value hash
 * @return {Style}
 * @api public
 */
Style.prototype.addRule = function (selector, style) {
    var rule = new Rule(selector, style)
    var sheet = this.element.sheet
    sheet.insertRule(rule.text, sheet.cssRules.length)
    this.rules[rule.selector] = rule
    return rule
}

/**
 * Get a rule.
 *
 * @param {String} selector
 * @return {Rule}
 * @api public
 */
Style.prototype.getRule = function (selector) {
    return this.rules[selector]
}

/**
 * Convert rules to a css string.
 *
 * @api public
 * @return {String}
 */
Style.prototype.toString = function () {
    var str = ''
    var rules = this.rules

    for (var selector in rules) {
        str += rules[selector].text + '\n'
    }

    return str
}

/**
 * Create style element.
 *
 * @api private
 * @return {Element}
 */
Style.prototype.createElement = function () {
    var el = document.createElement('style')
    for (var name in this.attributes) el.setAttribute(name, this.attributes[name])

    return el
}
